# Generated by Django 5.1.7 on 2025-03-13 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='flag',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.flag'),
        ),
    ]
