# Generated by Django 5.1.7 on 2025-03-14 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_produto_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.flag'),
        ),
    ]
