# Generated by Django 4.1 on 2025-03-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(default='user', max_length=50)),
            ],
        ),
    ]
