# Generated by Django 4.1 on 2025-03-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('valor', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
